import uuid
from datetime import datetime
from sqlalchemy import String, Text, DateTime, JSON, func
from sqlalchemy.orm import Mapped, mapped_column
# pyrefly: ignore [missing-import]
from app.database import Base

class AISuggestion(Base):
    __tablename__ = "ai_suggestions"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    type: Mapped[str] = mapped_column(String(50), nullable=False)  # segment_rules, message_template
    input_prompt: Mapped[str] = mapped_column(Text, nullable=False)
    output_json: Mapped[dict] = mapped_column(JSON, nullable=False)  # Response generated by AI
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), nullable=False)

    def __repr__(self) -> str:
        return f"<AISuggestion {self.type} ({self.id})>"
